// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkbU5Nh8ONAAfQBaOY1q7UMJ4drgixH4',
    appId: '1:862872272959:android:bc09da9198aa13acb6788a',
    messagingSenderId: '862872272959',
    projectId: 'ifri-23ae3',
    storageBucket: 'ifri-23ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa5pKjYwftAAH4RKuWix55KwrDzaco5rE',
    appId: '1:862872272959:ios:aacafb4b3bdb9917b6788a',
    messagingSenderId: '862872272959',
    projectId: 'ifri-23ae3',
    storageBucket: 'ifri-23ae3.appspot.com',
    iosClientId: '862872272959-u9s15bod6pl5lb7r4vgsd4112ftvk2tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa5pKjYwftAAH4RKuWix55KwrDzaco5rE',
    appId: '1:862872272959:ios:aacafb4b3bdb9917b6788a',
    messagingSenderId: '862872272959',
    projectId: 'ifri-23ae3',
    storageBucket: 'ifri-23ae3.appspot.com',
    iosClientId: '862872272959-u9s15bod6pl5lb7r4vgsd4112ftvk2tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifri',
  );
}
